
data_path: ./data
logger:
  dir: ./exp
  name: vq_vae
  

dataset:
  img_size: 512
  batch_size: 16
  num_workers: 8
  drop_last: false
  shuffle: false
  pin_memory: false
  
network:
  vq_vae:
    in_channels: 3
    embedding_dim: 512
    num_embeddings: 512
    num_layers: 6

optimizer:
  lr: 1e-4
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  eps: 1e-8

train:
  num_epochs: 100
  save_interval: 10
  save_ckpt_interval: 10
  save_img_interval: 10
  save_loss_interval: 10
  save_vis_interval: 10


loss:
  l1_loss:
    weight: 1.0
  perceptual_loss:
    weight: 1.0
    perceptual_loss_type: vgg
    perceptual_loss_layer: 16
    perceptual_loss_feature_dim: 512
